server:
  port: 8080


spring:
  security:
    user:
      name: admin
      password: 123
  datasource:
    url: jdbc:mysql://localhost:3306/identity
    username: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/identity?useSSL=false&serverTimezone=UTC
    user: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: mysql

  logging:
    level:
      root: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
  override-with-generic-response: false

